config/routes.rb
Bdhf::Application.routes.draw do
  get "homes" => "homes#index"
  get "homes/search"

  root :to => "content#homepage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/content_controller.rb
class ContentController < ApplicationController

  def homepage
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  PER_PAGE = 20

  before_filter :build_default_query, only: [:index]
  before_filter :build_query, only: [:search]
  before_filter :execute_query
  before_filter :calculate_pagination

  def index
  end

  def search
  end

private

  def build_query
    @terms = {
      area:  params[:area],
    }

    if max = params[:max]
      @terms[:price] = "* TO #{max}"
    end
  end

  def build_default_query
    @terms = {
      area: "Chicago, IL"
    }
  end

  def execute_query
    begin
      @listings, @meta = Homefinder.search(@terms)
    rescue => e
      logger.error e

      @no_results = true
    end
  end

  def calculate_pagination
    return if @no_results

    page_index = @meta["currentPage"]

    @first_index = (PER_PAGE * (page_index - 1)) + 1
    @last_index = PER_PAGE * page_index
    @total = @meta["totalMatched"]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/homes_helper.rb
# Some of these helpers operate on hashes with string (NOT symbol) keys that
# come directly from lib/homefinder, our HTTParty wrapper around the homefinder
# API
#
# TODO: move these into instance methods of lib/homefinder
module HomesHelper

  DATETIMEFORMAT = '%m/%d/%Y'

  def listing_date(str)
    Date.parse(str).strftime(DATETIMEFORMAT)
  end

  # Rails 3.2 uses Ordered Hashes, so we can retrieve the k,v pairs in the order they were inserted
  def address_parts(address)
    return {} unless address

    {
      line1:    address['line1'],
      line2:    address['line2'],
      city:     address['city'],
      state:    address['state'],
      zip:      address['zip']
    }.keep_if { |k, v| v.present? }
  end

  def one_line_address(address)
    format_address address_parts(address)
  end

  def google_maps_address(address)
    format_address address_parts(address).except(:line2)
  end

  def format_address(parts)
    [
      parts.except(:zip).values.join(', '),
      parts[:zip]
    ].keep_if{ |v| v.present? }.join(' ')
  end

  def link_to_google_maps(address, text = nil)
    return unless formatted_address = google_maps_address(address)

    text ||= 'View in Google Maps'
    url = 'https://maps.google.com/maps?q=' + CGI::escape(formatted_address)

    link_to text, url
  end

  def link_to_homefinder_url(url)
    return unless url

    text ||= "View on Homefinder.com"

    link_to text, url
  end

  def link_to_external_url(link_hash)
    return unless link_hash
    return unless text = link_hash["label"]
    return unless url  = link_hash["url"]

    link_to text, url
  end

  def offsite_links(listing)
    [
      link_to_homefinder_url( listing["url"]         ),
      link_to_google_maps(    listing["address"]     ),
      link_to_external_url(   listing["externalUrl"] )
    ].keep_if{ |v| v.present? }
  end

  def offsite_links_markup(listing)
    return unless links = offsite_links(listing)

    content_tag :ul, safe_join(links.map{ |link| content_tag(:li, link) })
  end

  def listing_description(listing)
    return "No description available" unless description = listing["description"]

    description
  end

  def listing_image(listing)
    return unless hsh = listing["primaryPhoto"]
    return unless url = hsh["url"]

    image_tag url, alt: one_line_address(listing["address"])
  end

  def listing_price(listing)
    return "Unknown" unless price = listing["price"]

    number_to_currency price, precision: 0
  end
end

app/views/content/homepage.html.erb
<h1>Welcome</h1>

<%= link_to "Browse and search for your next home", homes_path %>

app/views/homes/_form.html.erb
<div class="searchForm">
  <%= form_tag(homes_search_path, method: "get") do %>
    <fieldset>
      <legend>Search</legend>

      <%= label_tag :area, "ZIP Code" %>
      <%= text_field_tag :area, params[:area] %>

      <%= label_tag :max, "Maximum price" %>
      <%= text_field_tag :max, params[:max] %>

      <%= content_tag(:button, "Find My Next Home", type: 'submit') %>
    </fieldset>
  <% end %>
</div>

app/views/homes/_listing.html.erb
<article class="listing">

  <header>
    <%= content_tag(:h4, one_line_address(listing["address"])) %>

    <h5>
      Listed at <span><%= listing_price(listing) %></span>
      &raquo;
      Listed since <span><%= listing_date(listing["createDate"]) %></span>
      &raquo;
      Last updated <span><%= listing_date(listing["updateDate"]) %></span>
    </h5>
  </header>

  <%= content_tag :p do %>
    <%= listing_image listing %>
    <%= listing_description(listing) %>
  <% end %>

  <%= offsite_links_markup(listing) %>

  <%# DEBUG TOOL: uncomment to see all data returned %>
  <%#= content_tag :dl do %>
    <%#= listing.each_pair do |key, val| %>
      <%#= content_tag :dt, key %>
      <%#= content_tag :dd, val %>
    <%# end %>
  <%# end %>
</article>

app/views/homes/_listings.html.erb
<div class="listings"> 
  <%- if @no_results -%>

    <h3>We're sorry</h3>

    <p>Your search terms didn't turn up any homes. Care to try again?</p>

  <%- else -%>

    <h3>Displaying <%= @first_index %>-<%= @last_index %> of <%= @total %></h3>

    <%= render partial: 'listing', collection: listings %>

  <%- end %>
</div>

app/views/homes/index.html.erb
<% content_for :sidebar do %>
  <%= render 'form' %>
<% end %>

<h1>Browse Chicago homes</h1>

<%= render partial: 'listings', object: @listings %>

app/views/homes/search.html.erb
<% content_for :sidebar do %>
  <%= render 'form' %>
<% end %>

<h1>Search results</h1>

<%= render partial: 'listings', object: @listings %>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>HomeFinder.com Starter Application</title>
  <meta name="description" content="">

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    <%= content_tag(:p, flash[:error], class: 'flashError') if flash[:error] %>

    <div id="main" role="main">
      <%= yield %>
    </div>

    <%- if content_for? :sidebar -%>
      <aside id="sidebar">
        <%= content_for :sidebar %>
      </aside>
    <%- end -%>
  </div>


</body>
</html>